#! /bin/sh
#
# service        Start/stop service
#

### BEGIN INIT INFO
# Provides:          service
# Required-Start:    $remote_fs $network $named $time
# Required-Stop:     $remote_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts service
# Description:       Starts service, mostly Django-powered service.
### END INIT INFO

RUN=/usr/bin/run

test -e $RUN || exit 0

start()
{
    $RUN svc start >> /dev/null
}

stop()
{
    $RUN svc stop >> /dev/null
}

case "$1" in
    start)
    echo -n "Starting service..."
    start &
    ;;
    stop)
    echo -n "Stopping service..."
    stop &
    ;;
    *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
else
    echo " failed!"
fi

exit 0
